### ISSUE TITLE
When refreshing corpora it does not remove deleted folders from the list.

### ISSUE THREAD

**Issue by krismadden** [bootphon/seshat-angular-client#5]
In the campaign creation, http://localhost:4200/admin/campaign/create

I added a folder to the corpora folder. I refreshed the corpora and the folder appeared. I deleted the folder from the corpora folder. I refreshed the corpora and the folder is still there. I created a campaign with the deleted folder. I went into the campaign and it was showing files. I refreshed the files from there. The files disappeared. I returned to the campaign creation page, the deleted folder is still listed.

**Comment by hadware** [comment]
Well, I kind of thought about that, but there's no straightforward solution. It's all about database consistency.

See, a campaign object references a corpus object. If you delete that corpus, it leaves a "dangling" reference to the corpus. I can't set that reference to "null" because my campaign model's code assumes that a campaign's corpus is never "null" (and changing that is a bit of work, adding checks all over).

**Comment by hadware** [comment]
Solved in bootphon/seshat-restful-server@5be9ace94de6c0cf9ab78aaef5e4bdadc12cc615
